Initial commits, to main
Lillup/lillup-webapp pull request #1
Opened 2021-11-15 12:42 UTC by PbVrCt

Please take a quick glance at these commits and see if each commit is clear/modular enough or if we should operate in another way

2021-11-15 13:12 UTC, kj-crypto requested changes

2021-11-15 13:12 UTC, kj-crypto commented on components.d.ts
> +    ActionPageV1: typeof import('C:/projects/ampersand frontend/src/components/pages/layouts/actions/ActionPageV1.vue')['default']
Change absolute path into relative one

2021-11-15 13:18 UTC, PbVrCt commented on components.d.ts
> +    ActionPageV1: typeof import('C:/projects/ampersand frontend/src/components/pages/layouts/actions/ActionPageV1.vue')['default']
Ok, thanks. I will look into how to get the relative path, because that file is configured to be changed automatically every time you create/modify components. In fact I did not set those paths. It might not be trivial

2021-11-15 18:47 UTC, PbVrCt commented on components.d.ts
> +    ActionPageV1: typeof import('C:/projects/ampersand frontend/src/components/pages/layouts/actions/ActionPageV1.vue')['default']
Considering that the components.d.ts file sets the paths automatically based on a plugin and that manual changes to the paths are reverted back when saving, i´ve settled for adding the file to gitignore. I believe it is the best solution for our case.

2021-11-17 16:44 UTC, kj-crypto commented on components.d.ts
> +    ActionPageV1: typeof import('C:/projects/ampersand frontend/src/components/pages/layouts/actions/ActionPageV1.vue')['default']
I suppose that this file loads all needed components so ignoring it is not so good solution.
The problem is when you use absolute path like `C:/projects/ampersand frontend/src/components/pages/layouts/actions/ActionPageV1.vue` it's accessible only in your workstation. So we need relative path to component in project

2021-11-17 19:38 UTC, PbVrCt commented on components.d.ts
> +    ActionPageV1: typeof import('C:/projects/ampersand frontend/src/components/pages/layouts/actions/ActionPageV1.vue')['default']
The file contents are changed automatically by a plugin. Once you load the files locally on your editor then the paths should change automatically to the absolute paths in your machine, so it should be fine.

2021-11-17 20:16 UTC, PbVrCt commented on components.d.ts
> +    ActionPageV1: typeof import('C:/projects/ampersand frontend/src/components/pages/layouts/actions/ActionPageV1.vue')['default']
The plugin sets the contents of the file automatically. So if you were to download the files to your workstation and install everything needed, the paths in the file should change automatically to adapt to your machine.

Anyways, I´ve realized that later on, at the end, once running the build command to generate the distribution folder that ends up hosted somewhere, having the absolute paths might cause problems.

I´ll look for a way to replace them.

2021-11-23 05:59 UTC, closed without merging